Adaptation for Certificate creation
cloudio-project/cloudio-services pull request #7
Opened 2019-06-17 14:37 UTC by lucblender

Tested creation of certificate at startup, changed endpoint mongo id to UUID

2019-06-26 07:01 UTC, cm0x4D requested changes

2019-06-26 07:01 UTC, cm0x4D commented on src/main/kotlin/ch/hevs/cloudio2/cloud/AuthenticationService.kt
> +        if(endpointCredentialRepository.count() == 0L) {
I would not create a new endpoint if there are no endpoints present. It is the duty of a user to create endpoints when they are needed.

2019-06-26 07:01 UTC, cm0x4D commented on src/main/kotlin/ch/hevs/cloudio2/cloud/repo/authentication/EndpointCredential.kt
> +    var UUID: String ="",
An endpoint has no permissions nor does it have authorities - So you can remove this data class

2019-06-26 07:01 UTC, cm0x4D commented on src/main/kotlin/ch/hevs/cloudio2/cloud/internalservice/CertificateAndPrivateKey.kt
> +import java.io.Serializable
Using Java Serializable interface is not optimal, but it is the default when sending objects via AMQP. We should use JSON serialisation instead.

2019-07-03 12:15 UTC, lucblender commented on src/main/kotlin/ch/hevs/cloudio2/cloud/repo/authentication/EndpointCredential.kt
> +    var UUID: String ="",
Since we work now with UUID and "friendly name" for endpoint, we should keep the data class with only those two attributes?

2019-08-19 11:40 UTC, cm0x4D approved these changes

2019-08-19 14:12 UTC, merged